spring.application.name=iwanit

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=iwanit
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.port=8080

jwt.secret=${JWT_SECRET:pVOJEjRLoScmU4pRKHJugioAu2ffsNz6etSYWHtkOY4}
jwt.expiration-ms=86400000
